name: CI — Ejecutar Notebook

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace *.ipynb

      - name: Exportar notebook como HTML
        run: |
          jupyter nbconvert --to html *.ipynb

      - name: Guardar artefactos
        uses: actions/upload-artifact@v4
        with:
          name: notebook-html
          path: "*.html"